### ISSUE TITLE
Backgound doesn't get changed in dark mode

### ISSUE THREAD

**Issue by zubairehman** [gildaswise/rounded_modal#10]
Hi,

Thanks for such a great library.
My app supports both light and dark theme, upon changing theme, bottom sheet's background doesn't change.

**Comment by gildaswise** [comment]
Hey! This library is kinda outdated as of now because `showModalBottomSheet` now supports a radius on the beta channel, so it should be soon available in stable and that will automatically support your background changes!

But if you still want to use this: as the color of the sheet is set manually by the function's parameters, you'll have to either override the default color by copying the function somewhere or always set something like:

```dart
showRoundedModalBottomSheet(color: Theme.of(context).cardColor);
```
