### ISSUE TITLE
DropdownButtons doesn't work 

### ISSUE THREAD

**Issue by shinayser** [gildaswise/rounded_modal#3]
Hello!

Wish t report a bug that happens when you try to add a `DropDownButton `inside the modal:

![whatsapp image 2018-11-27 at 11 57 19](https://user-images.githubusercontent.com/1146982/49086753-674f2600-f23c-11e8-9a3c-c8c116361b71.jpeg)

As you can see, only a shadows appears.
If i change to the framework's default modal sheet (the square one) everything works fine.

**Comment by gildaswise** [comment]
Hey, sorry for the delay. As I'm using a "hack" of setting `canvasColor` to `Colors.transparent` so the corners appear, this makes some widgets that rely on Material to work in a funny way, and there's no apparent solution for that yet. I recommend using a full screen (remember to use `fullscreenDialog: true` when pushing) for this instead of a modal.
